// GENERATED by scripts/import-blog-posts.mjs — frontmatter of content/blog/*.mdx.
// Edit the .mdx source in dakio-landing and re-run the script, or edit here directly.

export const POST_META = [
  {
    "title": "একই ব্যবসা—তবু খরচে এত পার্থক্য কেন?",
    "slug": "same-business-different-cost",
    "category": "শুরু করুন",
    "date": "2026-06-01",
    "mins": 7,
    "excerpt": "একই প্রোডাক্ট ও একই ধরনের বিজ্ঞাপন—তবু খরচ আলাদা। কোথায় খরচ বাড়ে এবং কীভাবে কমাবেন, জানুন।",
    "featured": false,
    "thumb": "ink"
  },
  {
    "title": "Server-side tracking ছাড়া আপনার অ্যাড বাজেট কেন নষ্ট হচ্ছে",
    "slug": "server-side-tracking-ad-spend",
    "category": "মার্কেটিং",
    "date": "2026-05-12",
    "mins": 8,
    "excerpt": "সঠিক ট্র্যাকিং না থাকলে Meta অনেক বিক্রির তথ্যই পায় না। Server-side tracking দিয়ে সমস্যাটি কীভাবে কমাবেন, জানুন।",
    "featured": false,
    "thumb": "lime"
  },
  {
    "title": "কুরিয়ার রিটার্ন কেন আপনার লাভ খেয়ে ফেলছে — আর কীভাবে কমাবেন",
    "slug": "courier-returns-eating-profit",
    "category": "অর্ডার ম্যানেজমেন্ট",
    "date": "2026-05-12",
    "mins": 8,
    "excerpt": "রিটার্নে শুধু বিক্রি নয়—কুরিয়ার, প্যাকেজিং ও বিজ্ঞাপনের খরচও নষ্ট হয়। কারণ বোঝা এবং কমানোর উপায় জানুন।",
    "featured": true,
    "thumb": "ink"
  },
  {
    "title": "৫০ হাজার টাকার কম পুঁজিতে ই-কমার্স ব্যবসা শুরু করার উপায়",
    "slug": "start-ecommerce-under-50k",
    "category": "শুরু করুন",
    "date": "2026-05-08",
    "mins": 7,
    "excerpt": "ছোট বাজেটে প্রোডাক্ট যাচাই, স্টোর তৈরি ও বিজ্ঞাপন পরীক্ষা করে কীভাবে ই-কমার্স শুরু করবেন—ধাপে ধাপে জানুন।",
    "featured": false,
    "thumb": "cream"
  },
  {
    "title": "অসম্পূর্ণ অর্ডার: প্রতিদিনের যে বিক্রি হাতছাড়া হচ্ছে",
    "slug": "incomplete-orders-lost-sales",
    "category": "বিক্রি বাড়ান",
    "date": "2026-04-28",
    "mins": 7,
    "excerpt": "কাস্টমার কেন চেকআউট শেষ না করেই চলে যান, আর কীভাবে সেই হারানো বিক্রি ফিরিয়ে আনবেন—সহজভাবে জানুন।",
    "featured": false,
    "thumb": "lime"
  },
  {
    "title": "COD ব্যবসায় হিসাব রাখবেন কীভাবে — একদম সহজ গাইড",
    "slug": "cod-accounting-guide",
    "category": "অ্যাকাউন্টিং",
    "date": "2026-04-24",
    "mins": 7,
    "excerpt": "ক্যাশ অন ডেলিভারি ব্যবসায় অর্ডার, কুরিয়ার সেটেলমেন্ট, খরচ ও লাভ আলাদা করে রাখার সহজ পদ্ধতি।",
    "featured": false,
    "thumb": "ink"
  },
  {
    "title": "অর্ডার কনফার্ম কল: যেভাবে রিটার্ন কমাবেন",
    "slug": "order-confirmation-calls",
    "category": "অর্ডার ম্যানেজমেন্ট",
    "date": "2026-04-20",
    "mins": 7,
    "excerpt": "ছোট, পরিষ্কার ও সম্মানজনক কনফার্মেশন কল দিয়ে ভুল অর্ডার কুরিয়ারে যাওয়ার আগেই কীভাবে থামাবেন।",
    "featured": false,
    "thumb": "cream"
  },
  {
    "title": "ফেক অর্ডার চেনার ৫টি লক্ষণ — যেগুলো বেশিরভাগ সেলার এড়িয়ে যান",
    "slug": "spot-fake-orders",
    "category": "অর্ডার ম্যানেজমেন্ট",
    "date": "2026-04-15",
    "mins": 7,
    "excerpt": "একটি লক্ষণ দেখেই সিদ্ধান্ত নয়—কাস্টমারের ইতিহাস, ঝুঁকির সংকেত ও কনফার্মেশন মিলিয়ে ফেক অর্ডার যাচাই করুন।",
    "featured": false,
    "thumb": "lime"
  }
];
