// GENERATED by scripts/import-blog-posts.mjs — frontmatter of content/blog/*.mdx.
// Edit the .mdx source in dakio-landing and re-run the script, or edit here directly.

export const POST_META = [
  {
    "title": "একই ব্যবসা — কারো লাগে ১০ লাখ, কারো ২০ হাজার",
    "slug": "same-business-different-cost",
    "category": "শুরু করুন",
    "date": "2026-06-01",
    "mins": 7,
    "excerpt": "একই ছবি, একই বিজ্ঞাপন, একই দাম — তবু দুজনের খরচ এত পার্থক্য কেন? উত্তর লুকিয়ে আছে সিস্টেমে।",
    "featured": false,
    "thumb": "ink"
  },
  {
    "title": "Server-side tracking ছাড়া আপনার ad খরচ কেন নষ্ট হচ্ছে",
    "slug": "server-side-tracking-ad-spend",
    "category": "মার্কেটিং",
    "date": "2026-05-12",
    "mins": 8,
    "excerpt": "সঠিক ট্র্যাকিং ছাড়া বিজ্ঞাপনের বাজেটের বড় অংশ কোনো ফল ছাড়াই খরচ হয়ে যাচ্ছে। কীভাবে ঠিক করবেন জানুন।",
    "featured": false,
    "thumb": "lime"
  },
  {
    "title": "কুরিয়ার রিটার্ন কেন আপনার লাভ খেয়ে ফেলছে — আর কীভাবে কমাবেন",
    "slug": "courier-returns-eating-profit",
    "category": "অর্ডার ম্যানেজমেন্ট",
    "date": "2026-05-12",
    "mins": 8,
    "excerpt": "১০০টা অর্ডারের মধ্যে ৩০টা রিটার্ন আসলে পুরো মাসের লাভ শেষ। রিটার্নের কারণ বোঝা এবং কমানোর উপায় জানুন।",
    "featured": true,
    "thumb": "ink"
  },
  {
    "title": "৫০ হাজার টাকার কম পুঁজিতে ই-কমার্স ব্যবসা শুরু করার উপায়",
    "slug": "start-ecommerce-under-50k",
    "category": "শুরু করুন",
    "date": "2026-05-08",
    "mins": 6,
    "excerpt": "কম বিনিয়োগে কীভাবে একটি লাভজনক ই-কমার্স ব্যবসা শুরু করা যায় — ধাপে ধাপে গাইড।",
    "featured": false,
    "thumb": "cream"
  },
  {
    "title": "Incomplete order: যে ৩০% বিক্রি আপনি প্রতিদিন হারাচ্ছেন",
    "slug": "incomplete-orders-lost-sales",
    "category": "বিক্রি বাড়ান",
    "date": "2026-04-28",
    "mins": 5,
    "excerpt": "প্রতিদিনের ৩০% সম্ভাব্য বিক্রি incomplete অর্ডারের কারণে হারিয়ে যাচ্ছে। এটা কীভাবে ঠেকাবেন?",
    "featured": false,
    "thumb": "lime"
  },
  {
    "title": "COD ব্যবসায় হিসাব রাখবেন কীভাবে — একদম সহজ গাইড",
    "slug": "cod-accounting-guide",
    "category": "অ্যাকাউন্টিং",
    "date": "2026-04-24",
    "mins": 6,
    "excerpt": "ক্যাশ অন ডেলিভারি ব্যবসায় হিসাব রাখা কঠিন মনে হয়? এই সহজ পদ্ধতিতে সব ট্র্যাক করুন।",
    "featured": false,
    "thumb": "ink"
  },
  {
    "title": "অর্ডার কনফার্ম কল: যেভাবে করলে রিটার্ন প্রায় অর্ধেকে নামে",
    "slug": "order-confirmation-calls",
    "category": "অর্ডার ম্যানেজমেন্ট",
    "date": "2026-04-20",
    "mins": 5,
    "excerpt": "সঠিকভাবে অর্ডার কনফার্ম কল করলে রিটার্ন রেট প্রায় অর্ধেক কমিয়ে আনা সম্ভব।",
    "featured": false,
    "thumb": "cream"
  },
  {
    "title": "ফেক অর্ডার চেনার ৫টি লক্ষণ — যেগুলো বেশিরভাগ seller মিস করে",
    "slug": "spot-fake-orders",
    "category": "অর্ডার ম্যানেজমেন্ট",
    "date": "2026-04-15",
    "mins": 5,
    "excerpt": "ভুয়া অর্ডার শনাক্ত করার ৫টি সহজ লক্ষণ যেগুলো বেশিরভাগ সেলার এড়িয়ে যান।",
    "featured": false,
    "thumb": "lime"
  }
];
