// OG card claims, per route.
//
// **The cards are Latin-only in both locales, on purpose.**
//
// HANDOFF-NOTES gap #4 read this as a missing font. It isn't — vendoring Noto
// Sans Bengali and handing it to next/og renders the glyphs but does not shape
// them: satori has no Indic reordering, so the i-kar lands after its consonant
// instead of before it and unattached matras come out as dotted circles
// (verified on the /bn home card). A wrong-looking Bangla card is worse than an
// English one, so the bn pages share the English claim until the cards are
// generated by something with a real shaper.
//
// The Bangla lines below are written and ready — swap `ogClaim` to prefer them
// the day the card renderer can shape Bengali.

export const OG_KICKER = "DAKIO — THE COMMERCE OS FOR BANGLADESH";

const CLAIMS = {
  "/": {
    en: "Appoint an AI CEO to your online store.",
    bn: "আপনার দোকানে একজন AI CEO নিয়োগ দিন।",
  },
  "/nova": {
    en: "Your store's AI Acting CEO, on duty 24/7.",
    bn: "আপনার দোকানের AI Acting CEO, ২৪ ঘণ্টা ডিউটিতে।",
  },
  "/store": {
    en: "A store that runs itself.",
    bn: "যে দোকান নিজেই চলে।",
  },
  "/store-studio": {
    en: "Design a storefront without a developer.",
    bn: "ডেভেলপার ছাড়াই দোকান ডিজাইন করুন।",
  },
  "/grow": {
    en: "The business Grow Suite — see the curve bend.",
    bn: "ব্যবসা বাড়ানোর স্টুডিও — লাইনটা বেঁকে যেতে দেখুন।",
  },
  "/ads": {
    en: "Pick a product. Get the ad.",
    bn: "প্রোডাক্ট বাছুন। অ্যাড পেয়ে যান।",
  },
  "/front-office": {
    en: "AI that sells in your inbox.",
    bn: "যে AI আপনার ইনবক্সেই বিক্রি করে।",
  },
  "/switch": {
    en: "Switch from Shopify in one weekend.",
    bn: "এক উইকেন্ডেই Shopify ছেড়ে আসুন।",
  },
  "/pricing": {
    en: "Plans in taka. AI CEO included.",
    bn: "প্ল্যান টাকায়। সাথে AI CEO।",
  },
  "/about": {
    en: "Built in Bangladesh by Digidhaka.",
    bn: "বাংলাদেশে, Digidhaka-র তৈরি।",
  },
  "/blog": {
    en: "E-commerce growth guides, in Bangla and English.",
    bn: "ই-কমার্স বাড়ানোর গাইড, বাংলায়।",
  },
  "/contact": {
    en: "Talk to a human.",
    bn: "একজন মানুষের সাথে কথা বলুন।",
  },
};

/** Claim for a route. Always English — see the note at the top of this file. */
export const ogClaim = route => (CLAIMS[route] || CLAIMS["/"]).en;

export default CLAIMS;
